[package]
name = "storpulse-windows-service-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
storpulse-core.workspace = true
storpulse-windows-service-contract = { path = "../storpulse-windows-service-contract" }

[target.'cfg(windows)'.dependencies]
storpulse-windows-diagnostics = { path = "../storpulse-windows-diagnostics" }
storpulse-windows-ipc = { path = "../storpulse-windows-ipc" }
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Diagnostics_Etw",
  "Win32_System_Pipes",
  "Win32_System_SystemInformation",
  "Win32_System_Threading",
  "Win32_System_Time",
] }

[dev-dependencies]
serde_json.workspace = true
