[package]
name = "storpulse-windows-service-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
serde.workspace = true
storpulse-core.workspace = true
storpulse-windows-service-contract = { path = "../storpulse-windows-service-contract" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_Storage_FileSystem",
  "Win32_System_Diagnostics_Etw",
  "Win32_System_IO",
  "Win32_System_Pipes",
  "Win32_System_Threading",
] }

[dev-dependencies]
serde_json.workspace = true
